project_token: 20b455348337b18080026d14
name: TuriImageSimilarity
jobs:
  - job_id: ec8d101e-b3ce-4e91-a8cc-c6830a81ddd8
    language: python
    name: image_similarity
    entrypoint: "image_similarity.py"
    resources:
      requests:
        cpu: 6
        memory: 8Gi
      limits:
        cpu: 6
        memory: 8Gi
use_cache: false
